apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "odoo.fullname" . }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- else }}
  # Por padrão, mantém pelo menos 1 pod disponível quando replicaCount >= 2
  {{- if ge (int .Values.replicaCount) 2 }}
  minAvailable: 1
  {{- else }}
  minAvailable: 0
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "odoo.selectorLabels" . | nindent 6 }}

