apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo.fullname" . }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: longpolling
      port: {{ .Values.service.longpollingPort }}
      targetPort: longpolling
      protocol: TCP
  selector:
    {{- include "odoo.selectorLabels" . | nindent 4 }}
